version: '3'

services:
    entorn-php-apache:
        container_name: php-apache
        build:
            context: .
            dockerfile: DockerFile
        depends_on:
          - db
        volumes:
          - ./../gr3-bernabeu-rojas-picazo/ticketplanet:/var/www/html/
        ports:
          - 8081:80
    db:
        container_name: pg_container
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: usuario
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: ticketplanet
        volumes:
        - ./PostgresDb:/var/lib/postgresql
        ports:
          - "5432:5432"